# Generated by Django 3.1.7 on 2021-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
