# Generated by Django 3.1.7 on 2021-05-24 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saman',
            name='mfd',
            field=models.TimeField(default=datetime.datetime(2021, 5, 24, 12, 23, 38, 258123, tzinfo=utc)),
        ),
    ]
