# Generated by Django 3.1.7 on 2021-05-24 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0003_auto_20210524_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saman',
            name='mfd',
            field=models.TimeField(default=datetime.datetime(2021, 5, 24, 12, 26, 3, 892119, tzinfo=utc)),
        ),
    ]
