# Generated by Django 3.1.7 on 2021-05-25 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0006_auto_20210524_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('message', models.CharField(default='', max_length=500)),
                ('messaged', models.DateField(default=datetime.datetime(2021, 5, 25, 11, 21, 42, 632832, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='saman',
            name='mfd',
            field=models.TimeField(default=datetime.datetime(2021, 5, 25, 11, 21, 42, 632832, tzinfo=utc)),
        ),
    ]
