# Generated by Django 3.1.7 on 2021-05-25 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0007_auto_20210525_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messaged',
        ),
        migrations.AlterField(
            model_name='saman',
            name='mfd',
            field=models.TimeField(default=datetime.datetime(2021, 5, 25, 11, 33, 51, 658654, tzinfo=utc)),
        ),
    ]
