# Generated by Django 3.1.7 on 2021-05-25 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dukan', '0010_auto_20210525_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saman',
            name='mfd',
            field=models.TimeField(default=datetime.datetime(2021, 5, 25, 12, 17, 13, 383540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='saman',
            name='product_desc',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
